function show_ik(T0_6)
    dh = struct('alpha0', 0, ...
                'alpha1', -pi/2, ...
                'alpha2', 0, ...
                'alpha3', -pi/2, ...
                'alpha4', pi/2, ...
                'alpha5', -pi/2, ...
                'a0', 0, ...
                'a1', 0.04, ...
                'a2', 0.18, ...
                'a3', 0.055, ...
                'a4', 0, ...
                'a5', 0, ...
                'd1', 0.212, ...
                'd2', 0.062, ...
                'd3', -0.05, ...
                'd4', 0.205027, ...
                'd5', 0, ...
                'd6', 0);
    joint = IK_algorithm(T0_6,dh);
    
    base_xyz =[0 0 0];
    robot = puma560_robot(base_xyz);
    robot.display();    

    robot.plot(joint');             % 非交互式更新角度
    set(gca, 'XDir', 'reverse');   % 反转 x 轴方向 gca是获取当前坐标轴对象 XDir是x轴方向
    set(gca, 'YDir', 'reverse');   % 反转 y 轴方向
end